auth:
  token: mysecrettoken
  allowed_ips:
    - 127.0.0.1
log:
  file: /var/log/wakeonstorage.log
  level: 4
  max_size: 1048576
base_path: /api
sudo_path: /usr/bin/sudo
service_script: /usr/bin/php /opt/wakeOnStorage-local/bin/service
debug_ips:
  - 127.0.0.1
